In [1]:
using ViewerGL, LinearAlgebra
GL = ViewerGL
using LinearAlgebraicRepresentation
Lar = LinearAlgebraicRepresentation

using Plasm

In [3]:
function testarrangement(V,CV,FV,EV)
		cop_EV = Lar.coboundary_0(EV::Lar.Cells);
		cop_FE = Lar.coboundary_1(V, FV::Lar.Cells, EV::Lar.Cells);
		W = convert(Lar.Points, V');

#		V, copEV, copFE, copCF = Lar.Arrangement.spatial_arrangement(
		V, copEV, copFE, copCF = Lar.space_arrangement(
				W::Lar.Points, cop_EV::Lar.ChainOp, cop_FE::Lar.ChainOp);

		V = convert(Lar.Points, V');
		V,CVs,FVs,EVs = Lar.pols2tria(V, copEV, copFE, copCF) # whole assembly
		GL.VIEW(GL.GLExplode(V,FVs,1.1,1.1,1.1,99,1));
		GL.VIEW(GL.GLExplode(V,EVs,1.5,1.5,1.5,99,1));
		GL.VIEW(GL.GLExplode(V,CVs,1,1,1,99,1));
end


testarrangement (generic function with 1 method)

In [4]:
# primo, secondo e terzo cubo  => KO 

V = [0.6540618 0.7142365 0.5941251 0.6542998 1.3260341 1.3862088 1.2660973 1.326272 -0.3874063 0.3249123 -0.1702819 0.5420367 -0.317917 0.3944016 -0.1007926 0.611526 0.7899026 0.46601 0.804323 0.4804304 0.7905452 0.4666527 0.8049656 0.4810731 -0.2261907 -0.0499888 -0.0677963 0.1084056 0.0988343 0.2750362 0.2572286 0.4334306; 0.2054992 0.1455625 0.8769965 0.8170598 0.2707609 0.2108241 0.9422582 0.8823214 0.4902226 0.707347 -0.0864242 0.1307001 0.0663064 0.2834308 -0.5103404 -0.2932161 0.0605793 0.0749997 0.3844725 0.3988929 0.060565 0.0749854 0.3844582 0.3988786 -0.0720455 0.0863489 0.219164 0.3775584 -0.2998291 -0.1414347 -0.0086196 0.1497748; 0.2972308 0.969203 0.3624924 1.0344647 0.2428771 0.9148494 0.3081388 0.980111 0.4536339 0.5231232 0.0297177 0.099207 1.0658723 1.1353616 0.6419561 0.7114454 0.6679889 0.6686316 0.6679746 0.6686173 0.9922023 0.992845 0.992188 0.9928307 0.4715635 0.7965885 0.24378 0.5688049 0.4063673 0.7313923 0.1785838 0.5036087]


CV = [[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16], [17, 18, 19, 20, 21, 22, 23, 24]]

FV = [[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 5, 6], [3, 4, 7, 8], [1, 3, 5, 7], [2, 4, 6, 8], [9, 10, 11, 12], [13, 14, 15, 16], [9, 10, 13, 14], [11, 12, 15, 16], [9, 11, 13, 15], [10, 12, 14, 16], [17, 18, 19, 20], [21, 22, 23, 24], [17, 18, 21, 22], [19, 20, 23, 24], [17, 19, 21, 23], [18, 20, 22, 24]]

EV = [[1, 2], [3, 4], [5, 6], [7, 8], [1, 3], [2, 4], [5, 7], [6, 8], [1, 5], [2, 6], [3, 7], [4, 8], [9, 10], [11, 12], [13, 14], [15, 16], [9, 11], [10, 12], [13, 15], [14, 16], [9, 13], [10, 14], [11, 15], [12, 16], [17, 18], [19, 20], [21, 22], [23, 24], [17, 19], [18, 20], [21, 23], [22, 24], [17, 21], [18, 22], [19, 23], [20, 24]]

testarrangement(V,CV,FV,EV);


LoadError: InterruptException:

In [6]:
W = [0.6540617999999998 0.2054992 0.2972308000000001; 0.7142364999999998 0.1455625 0.969203; 0.6872816200343089 0.1724107693563844 0.6681972618528844; 0.5941250999999997 0.8769965 0.36249240000000005; 0.6542998079614951 0.8170598007732168 1.0344646993560203; 0.6929229746417847 0.3843473621810608 0.9924101013070119; 0.6660927570227951 0.3906268097799347 0.66824889023436; 0.6924256885846046 0.3894687221287142 0.9924113129852241; 1.3260341 0.2707609000000001 0.2428771; 1.3862088 0.21082410000000004 0.9148494000000003; 1.2660973 0.9422582000000003 0.3081388; 1.3262719920385087 0.8823213992267827 0.9801110006439793; 0.6540618 0.2054992 0.2972308; 0.7142365 0.14556250000000004 0.969203; 0.6872816200343091 0.17241076935638444 0.6681972618528844; 1.3260341000000002 0.2707609 0.24287709999999996; 1.3862087920795636 0.2108241887360494 0.9148494086241006; 0.7946185131077457 0.1533691699791747 0.9627011677876783; 0.795311803386693 0.18207414025178234 0.6679835359595829; 0.5941251 0.8769965000000001 0.36249240000000005; 0.6542997999999999 0.8170598000000001 1.0344647; 1.2660973 0.9422582000000002 0.3081388; 1.326271990374281 0.8823215078410288 0.9801110104808787; 0.6540617999999999 0.20549919999999997 0.2972308; 0.5941251 0.8769965000000001 0.3624924; 1.3260340999999998 0.27076089999999997 0.2428771; 1.2660972919751639 0.9422582079930893 0.3081387103865058; 0.7142365000000002 0.1455625 0.9692030000000001; 0.6542998 0.8170598 1.0344647000000002; 0.6929229720163114 0.3843473596022382 0.9924101013121028; 1.3862088000000001 0.2108241 0.9148494000000001; 1.3262720096034208 0.8823213904345382 0.9801111072417534; 0.794618512627164 0.1533691592257879 0.9627011668715635; 0.6978893364451173 0.3892254686183435 0.9924004714668809; 0.8049461769791598 0.3844586322271989 0.9823884300888783; -0.38740630000000004 0.49022260000000006 0.45363390000000015; 0.3249123 0.707347 0.5231232000000001; -0.17028190000000007 -0.08642419999999995 0.029717700000000125; 0.542036694733776 0.13070013212634024 0.09920695360173326; -0.317917 0.06630639999999999 1.0658723; 0.3944015999999999 0.28343080000000004 1.1353616; -0.10079260000000007 -0.5103404 0.6419561000000001; 0.6115259947337761 -0.2932160678736597 0.7114453536017331; 0.4729938678063347 0.07470259548304928 0.9819171231357612; 0.4673971777131105 0.08956648867512645 0.992844167328483; 0.4666328572520818 0.07498584149882567 0.9828352213039846; -0.3874063 0.4902226000000001 0.45363390000000003; 0.32491230000000004 0.7073470000000001 0.5231232000000001; -0.31791699999999995 0.06630639999999999 1.0658723; 0.39440160000000013 0.28343080000000004 1.1353616; -0.1702819 -0.08642419999999999 0.0297177; 0.5420366999999999 0.13070010000000004 0.09920700000000002; -0.10079260000000004 -0.5103403999999999 0.6419561000000001; 0.611526 -0.2932160999999999 0.7114454; -0.38740630000000004 0.49022260000000006 0.4536339; -0.17028190000000007 -0.08642419999999995 0.029717700000000014; -0.31791700000000006 0.0663064000000001 1.0658723; -0.10079260000000007 -0.5103404 0.6419561; 0.3249122999999999 0.7073470000000001 0.5231232; 0.5420366999999999 0.13070009999999987 0.09920699999999993; 0.3944015999999999 0.28343080000000015 1.1353616; 0.6115259999999999 -0.29321609999999987 0.7114453999999999; 0.46739718748369563 0.0895664566274823 0.9928441673077008; 0.47299386529046794 0.0747025955986248 0.9819171485642004; 0.4707836778272794 0.18222015069807973 0.6686268661789595; 0.4673140236772549 0.08983923498806379 0.9928443441979011; 0.5039882186318663 0.07330882745780876 0.6685562398308738; 0.7899025999999999 0.060579300000000016 0.6679888999999999; 0.46601 0.0749997 0.6686315999999999; 0.5039882186318663 0.07330882745780866 0.6685562398308738; 0.8043229999999999 0.38447249999999994 0.6679745999999999; 0.4804303999999999 0.3988929 0.6686172999999999; 0.6660927558316325 0.39062680983296777 0.6682488902367234; 0.7953118029802163 0.1820741311220082 0.6679835359599859; 0.4707836778272794 0.18222015069807973 0.6686268661789595; 0.6872816200343091 0.17241076935638439 0.6681972618528844; 0.7905452000000002 0.060564999999999994 0.9922023000000001; 0.46665270000000003 0.0749854 0.9928450000000001; 0.8049656 0.3844582 0.9921880000000001; 0.4810731000000001 0.3988786 0.9928307000000001; 0.697889326958961 0.38922546904068794 0.9924004714857043; 0.6924256856407727 0.3894687222597801 0.9924113129910656; 0.467314023677255 0.08983923498806395 0.9928443441979014; 0.6929229720163113 0.384347359602239 0.9924101013121028; 0.7899025999999999 0.06057930000000001 0.6679889; 0.46601 0.0749997 0.6686316; 0.5039882186318665 0.07330882745780865 0.6685562398308739; 0.7905452000000001 0.060565 0.9922022999999999; 0.46665269980217056 0.07498539555659997 0.992845000000196; 0.4666328571036896 0.07498583719164695 0.9828352431620289; 0.47299386691132567 0.07470259129389183 0.9819171453996192; 0.804323 0.38447249999999994 0.6679746000000001; 0.4804304 0.39889289999999994 0.6686173000000001; 0.6660927554861571 0.39062680984834913 0.6682488902374092; 0.8049656 0.38445819999999997 0.9921880000000001; 0.48107309980217067 0.39887859555659994 0.9928307000001961; 0.6978893329159805 0.3892254673036041 0.9924004714738189; 0.6924256857873373 0.38946872070628735 0.9924113129907065; 0.8049461769712758 0.3844586322273743 0.9823884261111371; 0.7899026 0.0605793 0.6679889; 0.804323 0.38447249999999994 0.6679746; 0.7953118031141145 0.1820741341294648 0.6679835359598533; 0.7905452 0.060564999999999994 0.9922022999999999; 0.8049656 0.3844582 0.9921879999999998; 0.8049461769605255 0.38445863222761356 0.9823884206872832; 0.7946185126271639 0.15336915922578792 0.9627011668715633; 0.46601 0.0749997 0.6686316; 0.4804304 0.3988929 0.6686173; 0.4707836778272794 0.18222015069807984 0.6686268661789596; 0.4666527 0.07498540000000001 0.992845; 0.4810731 0.3988786 0.9928306999999998; 0.46730119060869374 0.08955099446477009 0.9928443569238228; 0.4666328573001969 0.07498584149775507 0.9828352455759322];
Delta_0 = SparseArrays.sparse(([1, 4, 2, 5, 1, 2, 7, 3, 4, 3, 6, 5, 6, 8, 7, 9, 8, 9, 10, 12, 10, 13, 11, 12, 11, 13, 14, 17, 15, 18, 14, 15, 20, 16, 17, 16, 19, 18, 19, 21, 20, 21, 22, 24, 22, 25, 23, 24, 23, 25, 26, 28, 26, 29, 27, 28, 27, 29, 30, 33, 31, 35, 30, 31, 36, 32, 34, 32, 35, 33, 34, 38, 36, 37, 37, 38, 39, 41, 39, 42, 40, 41, 40, 42, 43, 45, 43, 46, 44, 45, 44, 48, 47, 48, 50, 46, 47, 49, 49, 50, 51, 53, 51, 54, 52, 53, 52, 54, 55, 57, 55, 58, 56, 57, 56, 58, 59, 61, 59, 62, 60, 61, 60, 62, 63, 67, 63, 68, 64, 67, 66, 68, 64, 65, 72, 65, 66, 70, 69, 71, 69, 72, 70, 71, 73, 77, 74, 79, 73, 74, 81, 75, 78, 76, 80, 75, 76, 82, 77, 78, 83, 79, 80, 81, 82, 83, 84, 88, 84, 89, 85, 88, 87, 90, 85, 86, 92, 86, 87, 91, 89, 90, 91, 92, 93, 96, 94, 97, 93, 94, 100, 95, 96, 95, 98, 97, 98, 99, 99, 100, 101, 106, 102, 108, 101, 102, 109, 103, 107, 105, 108, 103, 104, 110, 104, 105, 109, 106, 107, 110, 111, 114, 112, 115, 111, 112, 117, 113, 114, 113, 116, 115, 116, 118, 117, 118, 119, 123, 120, 125, 119, 120, 127, 121, 124, 122, 125, 121, 122, 126, 127, 123, 124, 126], [1, 1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 16, 16, 17, 17, 18, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 26, 27, 27, 28, 28, 29, 29, 30, 30, 30, 31, 31, 32, 32, 33, 33, 33, 34, 34, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 42, 42, 43, 43, 44, 44, 44, 45, 45, 45, 46, 46, 47, 47, 48, 48, 49, 49, 50, 50, 51, 51, 52, 52, 53, 53, 54, 54, 55, 55, 56, 56, 57, 57, 58, 58, 59, 59, 60, 60, 61, 61, 62, 62, 63, 63, 63, 64, 64, 64, 65, 65, 66, 66, 67, 67, 68, 68, 69, 69, 70, 70, 70, 71, 71, 72, 72, 73, 73, 73, 74, 74, 74, 75, 75, 75, 76, 76, 77, 77, 78, 78, 79, 79, 80, 80, 81, 81, 81, 82, 82, 82, 83, 83, 84, 84, 85, 85, 86, 86, 87, 87, 87, 88, 88, 89, 89, 90, 90, 90, 91, 91, 92, 92, 93, 93, 94, 94, 94, 95, 95, 96, 96, 97, 97, 97, 98, 98, 98, 99, 99, 99, 100, 100, 101, 101, 102, 102, 102, 103, 103, 104, 104, 105, 105, 105, 106, 106, 107, 107, 108, 108, 109, 109, 109, 110, 110, 111, 111, 112, 112, 112, 112, 113, 113, 113], Int8[-1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, -1, 1, 1, 1, 1]);
Delta_1 = SparseArrays.sparse([1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 3, 3, 3, 3, 4, 5, 4, 4, 5, 4, 4, 5, 4, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 9, 9, 8, 9, 9, 8, 9, 8, 9, 8, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 11, 11, 12, 11, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 17, 16, 16, 16, 16, 17, 16, 17, 16, 17, 16, 17, 18, 19, 20, 18, 18, 20, 19, 18, 18, 19, 18, 20, 18, 20, 21, 21, 22, 21, 21, 21, 21, 21, 22, 21, 22, 23, 24, 23, 23, 24, 23, 23, 24, 23, 24, 25, 26, 27, 25, 26, 25, 27, 26, 25, 26, 25, 27, 28, 29, 28, 28, 29, 28, 28, 29, 28, 29, 30, 31, 32, 31, 30, 32, 31, 30, 32, 30, 31], [1, 2, 3, 4, 5, 6, 7, 7, 8, 8, 9, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 20, 21, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 36, 37, 37, 38, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 49, 50, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 69, 70, 70, 71, 71, 72, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 81, 82, 82, 83, 83, 84, 85, 86, 87, 88, 89, 90, 91, 91, 92, 92, 93, 94, 95, 96, 97, 98, 99, 99, 100, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 109, 110, 110, 111, 112, 113, 114, 115, 116, 117, 117, 118, 118, 119, 120, 121, 122, 123, 124, 125, 126, 126, 127, 127], Int8[1, -1, -1, -1, 1, -1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, -1, 1, -1, -1, 1, 1, -1, 1, -1, -1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, -1]);
    

LoadError: syntax: incomplete: premature end of input

In [ ]:
julia> @show V;
3×39 Array{Float64,2}:
V = [0.6540617999999999 0.7142365 0.6872816200343091 0.5941250999999999 0.6542998026538317 0.692922972891469 0.6660927561135283 0.6924256866709048 1.3260341 1.3862087973598545 1.2660972973250546 1.326271997338737 0.7946185127873578 0.7953118031603413 0.6978893321066862 0.8049461769703203 -0.38740630000000004 0.3249123 -0.17028190000000007 0.542036698244592 -0.317917 0.39440159999999996 -0.10079260000000005 0.6115259982445921 0.4729938666693761 0.46739718259840307 0.46663285721865605 0.4707836778272794 0.46731402367725494 0.5039882186318664 0.7899026 0.46601 0.804323 0.4804303999999999 0.7905452000000001 0.46665269993405684 0.8049656 0.4810730999340569 0.46730119060869374; 0.2054992 0.14556250000000004 0.1724107693563844 0.8769965000000001 0.817059800257739 0.384347360461846 0.39062680982041725 0.3894687216982606 0.2707609 0.21082412957868316 0.9422582026643633 0.8823214325007832 0.15336916281025018 0.1820741351677518 0.3892254683208785 0.38445863222739557 0.49022260000000006 0.7073470000000001 -0.08642419999999996 0.13070011070878004 0.06630640000000003 0.2834308000000001 -0.5103404 -0.29321608929121984 0.07470259412518863 0.08956647265130438 0.07498584006274257 0.18222015069807976 0.08983923498806387 0.07330882745780869 0.06057930000000001 0.0749997 0.38447249999999994 0.39889289999999994 0.060565 0.07498539851886665 0.3844582 0.3988785985188667 0.08955099446477009; 0.2972308 0.9692030000000001 0.6681972618528844 0.36249240000000005 1.03446469978534 0.9924101013104059 0.6682488902361641 0.9924113129889988 0.24287709999999998 0.9148494028747004 0.3081387701288352 0.9801110394555371 0.962701167176935 0.6679835359598073 0.9924004714754681 0.9823884256290997 0.4536339000000001 0.5231232000000001 0.029717700000000045 0.09920698453391108 1.0658723 1.1353616 0.6419561000000001 0.7114453845339109 0.9819171390331937 0.9928441673180919 0.9828352366806485 0.6686268661789595 0.9928443441979012 0.6685562398308739 0.6679889 0.6686316 0.6679746 0.6686173000000001 0.9922022999999999 0.9928450000000654 0.992188 0.9928307000000652 0.9928443569238228]


In [ ]:
FE
32-element Array{Array{T,1} where T,1}:
 [1, 3, 4, 6, 7, 8, 9]
 [2, 5, 7, 8, 9]
 [10, 11, 12, 13]
 [1, 10, 14, 16, 17, 18]
 [2, 15, 17, 18]
 [3, 11, 19, 20]
 [4, 12, 14, 19]
 [5, 15, 21, 22, 23]
 [6, 13, 16, 20, 21, 22, 23]
 [24, 25, 26, 27]
 [28, 29, 30, 31, 33, 34, 35]
 [32, 34, 35]
 [24, 28, 36, 37]
 [25, 29, 38, 39]
 [26, 30, 36, 38]
 [27, 31, 33, 37, 39, 41, 42, 43, 44]
 [40, 41, 42, 43, 44]
 [45, 48, 49, 52, 53, 54, 55]
 [46, 51, 53]
 [47, 50, 54, 55]
 [56, 57, 59, 60, 61, 62, 63, 64]
 [58, 63, 64]
 [45, 56, 65, 67, 68, 69]
 [46, 66, 68, 69]
 [47, 58, 70, 9, 22]
 [48, 59, 72, 9]
 [57, 71, 22]
 [49, 60, 65, 71, 73, 74]
 [50, 70, 73, 74]
 [51, 66, 77, 78]
 [52, 76, 72, 78]
 [75, 67, 77]


In [ ]:
julia> @show EV;
78-element Array{Array{T,1} where T,1}:
EV = Array{T,1} where T[[1, 3], [2, 3], [4, 5], [1, 4], [2, 6], [5, 6], [3, 7], [6, 8], [7, 8], [9, 10], [11, 12], [9, 11], [10, 12], [1, 9], [2, 13], [10, 13], [3, 14], [13, 14], [4, 11], [5, 12], [6, 15], [15, 16], [13, 16], [17, 18], [19, 20], [17, 19], [18, 20], [21, 22], [23, 24], [21, 23], [22, 26], [25, 26], [24, 25], [26, 27], [25, 27], [17, 21], [18, 22], [19, 23], [20, 24], [26, 25], [28, 29], [25, 30], [28, 30], [26, 29], [31, 30], [32, 30], [33, 7], [34, 7], [31, 14], [33, 14], [32, 28], [34, 28], [30, 28], [7, 3], [14, 3], [35, 36], [37, 15], [15, 8], [38, 8], [35, 37], [36, 29], [38, 29], [8, 6], [15, 6], [31, 35], [32, 27], [36, 27], [27, 25], [30, 25], [33, 16], [37, 16], [34, 38], [14, 13], [16, 13], [36, 39], [38, 39], [39, 27], [28, 39]]

In [ ]:
function arrange3Dfaces(V, copEV, copFE)
	EVs = Lar.FV2EVs(copEV, copFE) # polygonal face fragments

	triangulated_faces = Lar.triangulate2D(V, [copEV, copFE])
	FVs = convert(Array{Lar.Cells}, triangulated_faces)
	V = convert(Lar.Points,V')
	return V,FVs,EVs
end

In [ ]:
julia> EVs = Lar.FV2EVs(copEV, copFE)
32-element Array{Array{Array{Int64,1},1},1}:
 [[1, 3], [4, 5], [1, 4], [5, 6], [3, 7], [6, 8], [7, 8]]
 [[2, 3], [2, 6], [3, 7], [6, 8], [7, 8]]
 [[9, 10], [11, 12], [9, 11], [10, 12]]
 [[13, 15], [16, 17], [13, 16], [17, 18], [15, 19], [18, 19]]
 [[14, 15], [14, 18], [15, 19], [18, 19]]
 [[20, 21], [22, 23], [20, 22], [21, 23]]
 [[24, 25], [26, 27], [24, 26], [25, 27]]
 [[28, 30], [28, 33], [30, 34], [34, 35], [33, 35]]
 [[29, 30], [31, 32], [31, 33], [29, 32], [30, 34], [34, 35], [33, 35]]
 [[36, 37], [38, 39], [36, 38], [37, 39]]
 [[40, 41], [42, 43], [40, 42], [41, 45], [43, 44], [45, 46], [44, 46]]
 [[44, 45], [45, 46], [44, 46]]
 [[47, 48], [49, 50], [47, 49], [48, 50]]
 [[51, 52], [53, 54], [51, 53], [52, 54]]
 [[55, 56], [57, 58], [55, 57], [56, 58]]
 [[59, 60], [61, 63], [62, 64], [59, 61], [60, 62], [65, 66], [64, 67], [65, 67], [63, 66]]
 [[63, 64], [65, 66], [64, 67], [65, 67], [63, 66]]
 [[68, 70], [72, 73], [68, 74], [72, 75], [70, 75], [73, 76], [74, 76]]
 [[69, 70], [69, 75], [70, 75]]
 [[71, 73], [71, 74], [73, 76], [74, 76]]
 [[77, 78], [79, 81], [80, 82], [77, 79], [78, 83], [80, 83], [82, 84], [81, 84]]
 [[81, 82], [82, 84], [81, 84]]
 [[85, 87], [88, 89], [85, 88], [89, 90], [90, 91], [87, 91]]
 [[86, 87], [86, 90], [90, 91], [87, 91]]
 [[92, 94], [97, 98], [92, 99], [94, 98], [97, 99]]
 [[93, 94], [96, 98], [93, 96], [94, 98]]
 [[95, 97], [95, 99], [97, 99]]
 [[100, 102], [103, 104], [100, 103], [104, 105], [102, 106], [105, 106]]
 [[101, 102], [101, 105], [102, 106], [105, 106]]
 [[107, 109], [107, 113], [112, 113], [109, 112]]
 [[108, 109], [111, 112], [108, 111], [109, 112]]
 [[110, 112], [110, 113], [112, 113]]


In [ ]:
Z = [0.6540617999999998 0.2054992 0.2972308000000001; 0.7142364999999998 0.1455625 0.969203; 0.6872816200343089 0.1724107693563844 0.6681972618528844; 0.5941250999999997 0.8769965 0.36249240000000005; 0.6542998079614951 0.8170598007732168 1.0344646993560203; 0.6929229746417847 0.3843473621810608 0.9924101013070119; 0.6660927570227951 0.3906268097799347 0.66824889023436; 0.6924256885846046 0.3894687221287142 0.9924113129852241; 1.3260341 0.2707609000000001 0.2428771; 1.3862088 0.21082410000000004 0.9148494000000003; 1.2660973 0.9422582000000003 0.3081388; 1.3262719920385087 0.8823213992267827 0.9801110006439793; 0.7946185131077457 0.1533691699791747 0.9627011677876783; 0.795311803386693 0.18207414025178234 0.6679835359595829; 0.6978893364451173 0.3892254686183435 0.9924004714668809; 0.8049461769791598 0.3844586322271989 0.9823884300888783; -0.38740630000000004 0.49022260000000006 0.45363390000000015; 0.3249123 0.707347 0.5231232000000001; -0.17028190000000007 -0.08642419999999995 0.029717700000000125; 0.542036694733776 0.13070013212634024 0.09920695360173326; -0.317917 0.06630639999999999 1.0658723; 0.3944015999999999 0.28343080000000004 1.1353616; -0.10079260000000007 -0.5103404 0.6419561000000001; 0.6115259947337761 -0.2932160678736597 0.7114453536017331; 0.4729938678063347 0.07470259548304928 0.9819171231357612; 0.4673971777131105 0.08956648867512645 0.992844167328483; 0.4666328572520818 0.07498584149882567 0.9828352213039846; 0.4707836778272794 0.18222015069807973 0.6686268661789595; 0.4673140236772549 0.08983923498806379 0.9928443441979011; 0.5039882186318663 0.07330882745780876 0.6685562398308738; 0.7899025999999999 0.060579300000000016 0.6679888999999999; 0.46601 0.0749997 0.6686315999999999; 0.8043229999999999 0.38447249999999994 0.6679745999999999; 0.4804303999999999 0.3988929 0.6686172999999999; 0.7905452000000002 0.060564999999999994 0.9922023000000001; 0.46665270000000003 0.0749854 0.9928450000000001; 0.8049656 0.3844582 0.9921880000000001; 0.4810731000000001 0.3988786 0.9928307000000001];
copEZ = SparseArrays.sparse([1, 4, 14, 2, 5, 15, 1, 2, 7, 17, 3, 4, 19, 3, 6, 20, 5, 6, 8, 21, 7, 9, 46, 47, 8, 9, 54, 55, 10, 12, 14, 10, 13, 16, 11, 12, 19, 11, 13, 20, 15, 16, 18, 23, 17, 18, 48, 49, 21, 22, 53, 54, 22, 23, 62, 63, 24, 26, 36, 24, 27, 37, 25, 26, 38, 25, 27, 39, 28, 30, 36, 28, 31, 37, 29, 30, 38, 29, 33, 39, 32, 33, 35, 41, 31, 32, 34, 43, 65, 66, 67, 34, 35, 60, 61, 40, 42, 50, 51, 67, 40, 43, 57, 58, 41, 42, 44, 45, 44, 48, 59, 45, 50, 60, 46, 49, 62, 47, 51, 64, 52, 56, 59, 52, 57, 61, 65, 53, 56, 63, 55, 58, 64, 66], [1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 30, 30, 30, 30, 31, 31, 31, 32, 32, 32, 33, 33, 33, 34, 34, 34, 35, 35, 35, 36, 36, 36, 36, 37, 37, 37, 38, 38, 38, 38], Int8[-1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, 1, 1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]);
copZFE = SparseArrays.sparse([1, 4, 2, 5, 1, 6, 1, 7, 2, 8, 1, 9, 1, 2, 18, 20, 1, 2, 21, 22, 1, 2, 25, 26, 3, 4, 3, 6, 3, 7, 3, 9, 4, 7, 5, 8, 4, 9, 4, 5, 18, 20, 4, 5, 28, 29, 6, 7, 6, 9, 8, 9, 21, 22, 8, 9, 25, 27, 8, 9, 28, 29, 10, 13, 10, 14, 10, 15, 10, 16, 11, 13, 11, 14, 11, 15, 11, 16, 12, 17, 11, 16, 11, 12, 30, 32, 11, 12, 23, 24, 13, 15, 13, 16, 14, 15, 14, 16, 16, 17, 16, 17, 23, 24, 16, 17, 18, 19, 16, 17, 18, 23, 19, 24, 20, 25, 18, 26, 18, 28, 20, 29, 19, 30, 18, 31, 21, 23, 21, 27, 22, 25, 21, 26, 21, 28, 21, 21, 23, 28, 24, 30, 23, 32, 25, 29, 27, 28, 26, 31, 32, 31, 30, 31], [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 25, 25, 26, 26, 27, 27, 28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 34, 34, 35, 35, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 41, 41, 42, 42, 42, 42, 43, 43, 44, 44, 45, 45, 46, 46, 47, 47, 48, 48, 49, 49, 50, 50, 51, 51, 52, 52, 53, 53, 54, 54, 55, 55, 56, 56, 57, 58, 59, 59, 60, 60, 61, 61, 62, 62, 63, 63, 64, 64, 65, 66, 67, 67], Int8[1, 1, -1, -1, -1, 1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1, -1, 1, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1, -1, 1]);
size(Z),size(copEZ),size(copZFE) == ((38, 3), (67, 38), (32, 67))

In [ ]:
# complesso da julia> FE prima di TGW 3d
32-element Array{Array{Int64,1},1}:
 [1, 3, 4, 6, 7, 8, 9]
 [2, 5, 7, 8, 9]
 [10, 11, 12, 13]
 [1, 10, 14, 16, 17, 18]
 [2, 15, 17, 18]
 [3, 11, 19, 20]
 [4, 12, 14, 19]
 [5, 15, 21, 22, 23]
 [6, 13, 16, 20, 21, 22, 23]
 [24, 25, 26, 27]
 [28, 29, 30, 31, 33, 34, 35]
 [32, 34, 35]
 [24, 28, 36, 37]
 [25, 29, 38, 39]
 [26, 30, 36, 38]
 [27, 31, 33, 37, 39, 40, 41, 42, 43]
 [32, 40, 41, 42, 43]
 [7, 17, 42, 44, 47, 48, 51]
 [42, 45, 50]
 [7, 17, 46, 49]
 [8, 21, 52, 53, 55, 56, 57, 58]
 [8, 21, 54]
 [35, 41, 44, 52, 59, 61]
 [35, 41, 45, 60]
 [9, 22, 46, 54, 62]
 [9, 47, 55, 64]
 [22, 53, 63]
 [18, 23, 48, 56, 59, 63]
 [18, 23, 49, 62]
 [34, 50, 60, 67]
 [51, 64, 66, 67]
 [34, 61, 65]

In [ ]:
julia>@show Lar.cop2lar(SparseArrays.sparse(copZFE'));
67-element Array{Array{Int64,1},1}:
[[1, 4],
 [2, 5],
 [1, 6],
 [1, 7],
 [2, 8],
 [1, 9],
 [1, 2, 18, 20],
 [1, 2, 21, 22],
 [1, 2, 25, 26],
 [3, 4],
 [3, 6],
 [3, 7],
 [3, 9],
 [4, 7],
 [5, 8],
 [4, 9],
 [4, 5, 18, 20],
 [4, 5, 28, 29],
 [6, 7],
 [6, 9],
 [8, 9, 21, 22],
 [8, 9, 25, 27],
 [8, 9, 28, 29],
 [10, 13],
 [10, 14],
 [10, 15],
 [10, 16],
 [11, 13],
 [11, 14],
 [11, 15],
 [11, 16],
 [12, 17],
 [11, 16],
 [11, 12, 30, 32],
 [11, 12, 23, 24],
 [13, 15],
 [13, 16],
 [14, 15],
 [14, 16],
 [16, 17],
 [16, 17, 23, 24],
 [16, 17, 18, 19],
 [16, 17],
 [18, 23],
 [19, 24],
 [20, 25],
 [18, 26],
 [18, 28],
 [20, 29],
 [19, 30],
 [18, 31],
 [21, 23],
 [21, 27],
 [22, 25],
 [21, 26],
 [21, 28],
 [21],
 [21],
 [23, 28],
 [24, 30],
 [23, 32],
 [25, 29],
 [27, 28],
 [26, 31],
 [32],
 [31],
 [30, 31]]